// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfwjpgidmxzhgmqpxihv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmd2pwZ2lkbXh6aGdtcXB4aWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTAzNzEsImV4cCI6MjA2NDAyNjM3MX0.jMki_HtINto7VnsgtXgmQ8GTdKxyVd1exC7oCFJ7Tzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);